### ISSUE TITLE
금요일 PR 반영

### ISSUE THREAD

**Issue by nerdyinu** [astraum/sidedish#32]
namse PR 반영

**Comment by happyGyu** [comment]
1. themes라는 애매한 네이밍 변경 (specialCategory)
2. key 추가
3. fetch에 try-catch 적용(에러 화면 구현 예정)
4. fetch에서 extended를 고려하지 않고 컴포넌트에서 상수로 관리(displayTargetCategories)
5. fetch함수 통일 (useFetch)
